name: Java Maven Sonar Analyse

on:
  workflow_call:
    inputs:
      java-version:
        default: 11
        required: false
        type: number
      projectKey:
        default: null
        required: true
        type: string
    secrets:
      github-token:
        required: true
      sonar-token:
        required: true

jobs:
  sonar-analyze: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK ${{ inputs.java-version }} 
        uses: actions/setup-java@v3
        with:
          java-version: temurin
          distribution: temurin
          cache: maven # Memorizar dependências

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        run: |
          echo "Change directory..."
          cd app
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.projectKey }}
