name: Java Maven PMD Check Rules

on:
  workflow_call:
    inputs:
      version:
        description: 'PMD version'
        default: '6.53.0'
        required: false
        type: string
      source-path:
        description: 'Source Path to Analyse'
        default: 'app/src'
        required: false
        type: string
      rulesets:
        description: 'Rulesets file path'
        default: 'app/pmd-ruleset.xml'
        required: false
        type: string


jobs:
  pmd-check-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run PMD Check Rules
        uses: pmd/pmd-github-action@v1
        id: pmd-check
        with:
          version: ${{ inputs.version }}
          sourcePath: ${{ inputs.source-path }}
          rulesets: ${{ inputs.rulesets }}
          analyzeModifiedFilesOnly: false

      - name: No PMD Rules Violation
        if: steps.pmd-check.outputs.violations == 0
        run: |
          echo "No violation of the PMD Rules. Congratulations! :)"         

      - name: PMD Rules Violations
        if: steps.pmd-check.outputs.violations != 0
        run: |
          echo "Number of Violations: ${{ steps.pmd-check.outputs.violations }} - (Must be Zero!!!)"
          echo "Check previous step for more details!!!"
          exit 1
