on:
  workflow_call:
    inputs:
      java-version:
        default: 11
        required: false
        type: number
      projectKey:
        default: null
        required: true
        type: string

jobs:
  sonarcloud-java-maven: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK ${{ inputs.java-version }} 
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: temurin 
          cache: maven # Memorizar dependências

      - name: Cache SonarCloud Packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "changing to app directory..."
          cd app
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=${{ inputs.projectKey }}
